1.12. Начинаем программировать
htmlacademy-react/1160585-six-cities-7 pull request #3
Opened 2021-06-06 17:50 UTC by tkadlets

2021-06-07 03:06 UTC, klimnikova requested changes

2021-06-07 03:06 UTC, klimnikova commented on project/src/components/app/app.jsx
>  import React from 'react';
зачем эти комментарии?

2021-06-07 03:06 UTC, klimnikova commented on project/src/components/home/card.jsx
> +    mark: PropTypes.string,
если объект data необязательный, то надо передать ему defaultProps. Но, наверное, у тебя он все-таки обязательный

2021-06-07 03:06 UTC, klimnikova commented on project/src/components/home/index.jsx
> +                    <span>Paris</span>
города желательно вынести в массив и пройтись по нему циклом - паттерн DRY

2021-06-07 03:06 UTC, klimnikova commented on project/src/components/home/index.jsx
> +                    <li className="places__option places__option--active" tabIndex="0">Popular</li>
аналогично с массивом - опции выпадашки

2021-06-07 03:08 UTC, klimnikova commented on project/src/components/home/index.jsx
> +
у нас файлы называются по имени компонента: Home.jsx

2021-06-07 03:10 UTC, klimnikova commented on project/src/components/home/card.jsx
> +import React from 'react';
для компонента card лучше создать свою директорию и поместить туда

2021-06-07 03:13 UTC, klimnikova commented
8,9 пункты задания не выполнены

2021-06-10 15:59 UTC, tkadlets commented on project/src/components/home/index.jsx
> +                    <li className="places__option places__option--active" tabIndex="0">Popular</li>
сделала, но они у меня пока все с классом --active, не разобралась, как это решить

2021-06-11 05:05 UTC, klimnikova approved these changes

2021-06-11 05:05 UTC, klimnikova commented on project/src/components/home/home.jsx
> +                    ))}
по поводу класса `active`: воспользуемся пакетом classnames и в state будем хранить активную опцию: 
`const [activeItem, setActive] = useState('Popular')`
```
 <li key = {item.id} className={classNames('places__option', {places__option--active: item.name === activeItem})} tabIndex="0" onClick={() => setActive(item.name} >{item.name}</li>
```

2021-06-11 05:05 UTC, merged